import * as THREE from "https://unpkg.com/three@0.128.0/build/three.module.js";
import { OrbitControls } from "https://unpkg.com/three@0.128.0/examples/jsm/controls/OrbitControls.js";

const cornersMap = new Map([
  ["UBL", 0], ["UBR", 1], ["UFL", 2], ["LBU", 3], ["LFU", 4], ["LDF", 5], ["LDB", 6],
  ["FUL", 7], ["FDR", 8], ["FDL", 9], ["RUB", 10], ["RDB", 11], ["RDF", 12], ["BUR", 13],
  ["BUL", 14], ["BDL", 15], ["BDR", 16], ["DFL", 17], ["DFR", 18], ["DBR", 19], ["DBL", 20]
]);

const edgesMap = new Map([
  ["UB", 0], ["UR", 1], ["UL", 2], ["LU", 3], ["LF", 4], ["LD", 5], ["LB", 6],
  ["FR", 7], ["FD", 8], ["FL", 9], ["RU", 10], ["RB", 11], ["RD", 12], ["RF", 13],
  ["BU", 14], ["BL", 15], ["BD", 16], ["BR", 17], ["DF", 18], ["DR", 19], ["DB", 20], ["DL", 21]
]);

const container = document.getElementById('three-container');
const scene = createScene();
const camera = createCamera();
const renderer = new THREE.WebGLRenderer();

const orbit = new OrbitControls(camera, renderer.domElement); 

// Set the renderer size and append the DOM element
renderer.setSize(window.innerWidth, window.innerHeight);
container.appendChild(renderer.domElement);

orbit.enableDamping = true;  // Optional: Enable damping for smoother movement
orbit.dampingFactor = 0.25;
orbit.screenSpacePanning = false;
//orbit.enableZoom = false;
orbit.maxDistance = 10;
orbit.minDistance = 5;
let cubelets = [];
let all_moves = [];

let isAnimating = false;
let animationQueue = [];
let currentPivotGroup = null;
let activeRotationLayers = [];
let currentAnimationAxis = '';
let currentAnimationDirection = 0;
let currentAnimationTargetAngle = 0;
let currentAnimationProgress = 0;
const ANIMATION_SPEED = 0.09;

document.addEventListener('DOMContentLoaded', () => {
    initialize();
    setupFormListener();
});

function initialize() {
    // generated by chatgpt 
    for (let i = scene.children.length - 1; i >= 0; i--) {
        const child = scene.children[i];
        if (child.type === 'Group') {
            scene.remove(child);
        }
    }
    cubelets = [];

    var ambientLight = new THREE.AmbientLight(0xffffff, 2);
    scene.add( ambientLight );

    var light = new THREE.DirectionalLight( 'white', 1 );
    light.position.set( 1, 1, 1 );
    scene.add( light );

    createCube(scene);
    camera.position.set(5, 2, 4);
    // orbit.target.set(0, -1, 0); // shift rotation target down
    // orbit.update();
    camera.lookAt(2, 1, 1); 
    scene.rotation.y = -Math.PI / 4 - Math.PI / 8;
    animate(cubelets, scene, camera, renderer, orbit);
}

// Function to handle canvas dimensions for high-DPI scaling
function setCanvasDimensions(canvas, width, height, set2dTransform = false) {
    const ratio = window.devicePixelRatio;  // Get device pixel ratio
    canvas.width = width * ratio;  // Scale the width
    canvas.height = height * ratio; // Scale the height
    canvas.style.width = `${width}px`;  // Set the style width
    canvas.style.height = `${height}px`;  // Set the style height

    if (set2dTransform) {
        canvas.getContext('2d').setTransform(ratio, 0, 0, ratio, 0, 0);
    }
}

// Adjust for resizing the window
window.addEventListener('resize', () => {
    const width = window.innerWidth;
    const height = window.innerHeight;

    camera.aspect = width / height;  // Update aspect ratio
    camera.updateProjectionMatrix();  // Update projection matrix
    renderer.setSize(width, height);  // Update the renderer size
    setCanvasDimensions(renderer.domElement, width, height);  // Handle high-DPI scaling
});

// Function to create the scene
function createScene() {
    const scene = new THREE.Scene();
    scene.background = new THREE.Color('black');
    return scene;
}

// Function to create the camera
function createCamera() {
    const camera = new THREE.PerspectiveCamera(90, window.innerWidth / window.innerHeight, 0.1, 1000);
    return camera;
}

function createCube(scene) {
    const cubeGroup = new THREE.Group(); // Create the group outside the loop

    // Colors for each face (you can customize this)
    const faceColors = [
        new THREE.MeshBasicMaterial({ color: 0x00ff00 }), // Green
        new THREE.MeshBasicMaterial({ color: 0x0000FF }), // Blue
        new THREE.MeshBasicMaterial({ color: 0xFFFFFF }), // White
        new THREE.MeshBasicMaterial({ color: 0xFFFF00 }), // Yellow
        new THREE.MeshBasicMaterial({ color: 0xFFA500 }), // Orange
        new THREE.MeshBasicMaterial({ color: 0xFF0000 })  // Red
    ];

    const geometry = new THREE.BoxGeometry(1, 1, 1);
    const spacing = 1.015;
    // Create the small cubes
    for (let z = -1; z <= 1; z++) {
        for (let y = -1; y <= 1; y++) {
            for (let x = -1; x <= 1; x++) {
                const materials = [
                    faceColors[0], // Front face (Green)
                    faceColors[1], // Back face (Blue)
                    faceColors[2], // Top face (White)
                    faceColors[3], // Bottom face (Yellow)
                    faceColors[4], // Left face (Orange)
                    faceColors[5]  // Right face (Red)
                ];

                const cube = new THREE.Mesh(geometry, materials);
                
                const edges = new THREE.EdgesGeometry(cube.geometry);
                const wireframe = new THREE.LineSegments(edges, new THREE.LineBasicMaterial({ color: 0x000000 }));
                cube.add(wireframe);

                // Create a group for each cube and add the cube and edge lines to it
                const cubeWithLineGroup = new THREE.Group();
                cubeWithLineGroup.add(cube);
                cubeWithLineGroup.position.set(x * spacing, y * spacing, z * spacing); // Position the cube in the grid
                cubelets.push(cubeWithLineGroup);
                cubeGroup.add(cubeWithLineGroup);          
            }
        }
    }
    scene.add(cubeGroup);
    //cubeGroup.position.y = -3;
    //cubeGroup.position.y = -3;
    return cubeGroup;
}

function rotateSide(axis, layer, direction) {
    const rotationAxis = new THREE.Vector3();
    rotationAxis[axis] = 1;
    const rotationMatrix = new THREE.Matrix4().makeRotationAxis(rotationAxis, direction * Math.PI / 2);
    cubelets.forEach(cubelet => {
        if (Math.round(cubelet.position[axis]) === layer) {
            cubelet.applyMatrix4(rotationMatrix);
            cubelet.position.round();
        }
    });
}

// handleRotations and rotateCube sets up the cube upon pressing "View Algorithm"
function handleRotations(rotations) {
    const axes = ['x', 'y', 'z'];
    const layers = [-1, 0, 1];
    const directions = [-1, 1];

    rotations.forEach(r => 
        {
            const axis = axes[r[0]];
            const layer = layers[r[1]];
            const direction = directions[r[2]];
            rotateSide(axis, layer, direction);
        })
    }

function rotateCube(moves) {
    const moveList = moves.trim().split(" ");
    all_moves = moveList
    const rotations = []
    moveList.forEach(move => {
        if (move === "F") {
            rotations.push([0, 2, 0]);
        }
        if (move === "F'") {
            rotations.push([0, 2, 1]);
        }
        if (move === "F2") {
            rotations.push([0, 2, 0]);
            rotations.push([0, 2, 0]);
        }
        if (move === "S") {
            rotations.push([0, 1, 0]);
        }
        if (move === "S'") {
            rotations.push([0, 1, 1]);
        }
        if (move === "B") {
            rotations.push([0, 0, 1]);
        }
        if (move === "B'") {
            rotations.push([0, 0, 0]);
        }
        if (move === "U'") {
            rotations.push([1, 2, 1])
        }
        if (move === "U") {
            rotations.push([1, 2, 0])
        }
        if (move === "U2" || move === "U2'") {
            rotations.push([1, 2, 0])
            rotations.push([1, 2, 0])
        }
        if (move === "D'") {
            rotations.push([1, 0, 0])
        }
        if (move === "D") {
            rotations.push([1, 0, 1])
        }
        if (move === "D2") {
            rotations.push([1, 0, 1])
            rotations.push([1, 0, 1])
        }
        if (move === "L") {
            rotations.push([2, 2, 0])
        }
        if (move === "L2") {
            rotations.push([2, 2, 0])
            rotations.push([2, 2, 0])
        }
        if (move === "L'") {
            rotations.push([2, 2, 1])
        }
        if (move === "R'") {
            rotations.push([2, 0, 0])
        }
        if (move === "R") {
            rotations.push([2, 0, 1])
        }
        if (move === "R2") {
            rotations.push([2, 0, 1])
            rotations.push([2, 0, 1])
        }
        if (move === "Lw") {
            rotations.push([2, 2, 0])
            rotations.push([2, 1, 0])
        }
        if (move === "Lw'") {
            rotations.push([2, 2, 1])
            rotations.push([2, 1, 1])
        }
        if (move === "Uw") {
            rotations.push([1, 2, 0])
            rotations.push([1, 1, 0])
        }
        if (move === "Uw'") {
            rotations.push([1, 2, 1])
            rotations.push([1, 1, 1])
        }
        if (move == "x") {
            rotations.push([2, 2, 1])
            rotations.push([2, 1, 1])
            rotations.push([2, 0, 1])
        }
        if (move == "x'") {
            rotations.push([2, 2, 0])
            rotations.push([2, 1, 0])
            rotations.push([2, 0, 0])
        }
        if (move == "M2") {
            rotations.push([2, 1, 0]);  
            rotations.push([2, 1, 0]);  
        }
        if (move == "E2") {
            rotations.push([1, 1, 0]);
            rotations.push([1, 1, 0]);
        }
        if (move === "M") {
            rotations.push([2, 1, 0]);     
        }
        if (move === "M'") {
            rotations.push([2, 1, 1]);
        }
        if (move === "E") {
            rotations.push([1, 1, 1]);   
        }   
        if (move === "E'") {
            rotations.push([1, 1, 0]);
        }
        if (move == "Rw") {
            rotations.push([2, 1, 1]);
            rotations.push([2, 0, 1])
        }
        if (move == "Rw'") {
            rotations.push([2, 1, 0]);
            rotations.push([2, 0, 0])
        }
        if (move == "Uw2") {
            rotations.push([1, 1, 0]);
            rotations.push([1, 1, 0]);
            rotations.push([1, 2, 0])
            rotations.push([1, 2, 0])
        }
    });
    handleRotations(rotations)
    handleRotations(rotations)
}

// Function to animate the cube
function animate(cube, scene, camera, renderer, orbit) {
    function animateLoop() {
        requestAnimationFrame(animateLoop);  
        
        // Correctly processes active pivot rotation transformations
        if (isAnimating && currentPivotGroup && activeRotationLayers.length > 0) {
            const axis = activeRotationLayers[0].axis;
            const direction = activeRotationLayers[0].direction;
            const multiplier = activeRotationLayers[0].multiplier;
            
            const totalTargetAngle = direction * (Math.PI / 2) * multiplier;
            let step = totalTargetAngle * ANIMATION_SPEED;
            
            currentAnimationProgress += step;
            currentPivotGroup.rotation[axis] += step;

            // Check if rotation has fully satisfied transition angle goals
            if (Math.abs(currentAnimationProgress) >= Math.abs(totalTargetAngle)) {
                currentPivotGroup.rotation[axis] = totalTargetAngle;
                
                // Clear pivot structures and return pieces to global hierarchy
                const tempChildren = [...currentPivotGroup.children];
                tempChildren.forEach(cubelet => {
                    scene.attach(cubelet);
                    cubelet.position.round(); 
                });

                scene.remove(currentPivotGroup);
                currentPivotGroup = null;
                activeRotationLayers = [];
                currentAnimationProgress = 0;
                isAnimating = false;

                // Process the next move if the user was spamming keys
                if (animationQueue.length > 0) {
                    const nextMove = animationQueue.shift();
                    handleMove(nextMove);
                }
            }
        }

        orbit.update();  
        renderer.render(scene, camera);  
    }
    animateLoop();
}

// handles each move one by one 
function handleMove(move) {
    if (isAnimating) {
        animationQueue.push(move); // Queue moves if user presses arrows too fast
        return;
    }

    // This temporary array will collect the layers that need to move for this specific input
    // Each target format: { axis: 'x'|'y'|'z', layer: -1|0|1, direction: -1|1, multiplier: 1|2 }
    let targets = [];

    if (move === "F") {
        targets.push({ axis: 'x', layer: 1, direction: -1, multiplier: 1 });
    }
    if (move === "F'") {
        targets.push({ axis: 'x', layer: 1, direction: 1, multiplier: 1 });
    }
    if (move === "F2") {
        targets.push({ axis: 'x', layer: 1, direction: -1, multiplier: 2 });
    }
    if (move === "S") {
        targets.push({ axis: 'x', layer: 0, direction: -1, multiplier: 1 });
    }
    if (move === "S'") {
        targets.push({ axis: 'x', layer: 0, direction: 1, multiplier: 1 });
    }
    if (move === "B") {
        targets.push({ axis: 'x', layer: -1, direction: 1, multiplier: 1 });
    }
    if (move === "B'") {
        targets.push({ axis: 'x', layer: -1, direction: -1, multiplier: 1 });
    }
    if (move === "U") {
        targets.push({ axis: 'y', layer: 1, direction: -1, multiplier: 1 });
    }
    if (move === "U'") {
        targets.push({ axis: 'y', layer: 1, direction: 1, multiplier: 1 });
    }
    if (move === "U2" || move === "U2'") {
        targets.push({ axis: 'y', layer: 1, direction: -1, multiplier: 2 });
    }
    if (move === "D'") {
        targets.push({ axis: 'y', layer: -1, direction: -1, multiplier: 1 });
    }
    if (move === "D") {
        targets.push({ axis: 'y', layer: -1, direction: 1, multiplier: 1 });
    }
    if (move === "E") {
        targets.push({ axis: 'y', layer: 0, direction: 1, multiplier: 1 });
    }
    if (move === "E'") {
        targets.push({ axis: 'y', layer: 0, direction: -1, multiplier: 1 });
    }
    if (move === "E2") {
        targets.push({ axis: 'y', layer: 0, direction: -1, multiplier: 2 });
    }
    if (move === "D2") {
        targets.push({ axis: 'y', layer: -1, direction: 1, multiplier: 2 });
    }
    if (move === "L") {
        targets.push({ axis: 'z', layer: 1, direction: -1, multiplier: 1 });
    }
    if (move === "L2") {
        targets.push({ axis: 'z', layer: 1, direction: -1, multiplier: 2 });
    }
    if (move === "L'") {
        targets.push({ axis: 'z', layer: 1, direction: 1, multiplier: 1 });
    }
    if (move === "R'") {
        targets.push({ axis: 'z', layer: -1, direction: -1, multiplier: 1 });
    }
    if (move === "R") {
        targets.push({ axis: 'z', layer: -1, direction: 1, multiplier: 1 });
    }
    if (move === "R2") {
        targets.push({ axis: 'z', layer: -1, direction: 1, multiplier: 2 });
    }
    if (move === "Lw") {
        targets.push({ axis: 'z', layer: 1, direction: -1, multiplier: 1 });
        targets.push({ axis: 'z', layer: 0, direction: -1, multiplier: 1 });
    }
    if (move === "Lw'") {
        targets.push({ axis: 'z', layer: 1, direction: 1, multiplier: 1 });
        targets.push({ axis: 'z', layer: 0, direction: 1, multiplier: 1 });
    }
    if (move === "Uw") {
        targets.push({ axis: 'y', layer: 1, direction: -1, multiplier: 1 });
        targets.push({ axis: 'y', layer: 0, direction: -1, multiplier: 1 });
    }
    if (move === "Uw'") {
        targets.push({ axis: 'y', layer: 1, direction: 1, multiplier: 1 });
        targets.push({ axis: 'y', layer: 0, direction: 1, multiplier: 1 });
    }
    if (move === "M") {
        targets.push({ axis: 'z', layer: 0, direction: -1, multiplier: 1 });
    }
    if (move === "M'") {
        targets.push({ axis: 'z', layer: 0, direction: 1, multiplier: 1 });
    }
    if (move === "M2") {
        targets.push({ axis: 'z', layer: 0, direction: 1, multiplier: 2 });
    }
    if (move === "x") {
        targets.push({ axis: 'z', layer: 1, direction: 1, multiplier: 1 });
        targets.push({ axis: 'z', layer: 0, direction: 1, multiplier: 1 });
        targets.push({ axis: 'z', layer: -1, direction: 1, multiplier: 1 });
    }
    if (move === "x'") {
        targets.push({ axis: 'z', layer: 1, direction: -1, multiplier: 1 });
        targets.push({ axis: 'z', layer: 0, direction: -1, multiplier: 1 });
        targets.push({ axis: 'z', layer: -1, direction: -1, multiplier: 1 });
    }
    if (move === "Rw") {
        targets.push({ axis: 'z', layer: 0, direction: 1, multiplier: 1 });
        targets.push({ axis: 'z', layer: -1, direction: 1, multiplier: 1 });
    }
    if (move === "Rw'") {
        targets.push({ axis: 'z', layer: 0, direction: -1, multiplier: 1 });
        targets.push({ axis: 'z', layer: -1, direction: -1, multiplier: 1 });
    }
    if (move === "Uw2") {
        targets.push({ axis: 'y', layer: 1, direction: -1, multiplier: 2 });
        targets.push({ axis: 'y', layer: 0, direction: -1, multiplier: 2 });
    }

    if (targets.length > 0) {
        setupSmoothAnimation(targets);
    }
}

function setupSmoothAnimation(targets) {
    isAnimating = true;
    currentAnimationProgress = 0;
    activeRotationLayers = [];

    // Create a new pivot group for this rotation instance
    currentPivotGroup = new THREE.Group();
    scene.add(currentPivotGroup);

    // Read the primary target properties
    const primaryAxis = targets[0].axis;
    const multiplier = targets[0].multiplier; 
    
    // Store configurations for completion later
    activeRotationLayers = targets;

    // Filter out and temporarily grab all cubelets across any of the target layers
    cubelets.forEach(cubelet => {
        const matchesLayer = targets.some(t => Math.round(cubelet.position[primaryAxis]) === t.layer);
        if (matchesLayer) {
            currentPivotGroup.attach(cubelet); // attach preserves world space coordinates!
        }
    });
}

function getInverseMove(move) {
    if (move.endsWith("2") || move.endsWith("2'")) {
        return move; // 180-degree turns are their own inverse
    } else if (move.endsWith("'")) {
        return move.slice(0, -1); // Remove the apostrophe
    } else {
        return move + "'"; // Add the apostrophe
    }
}

function displayMoves(movesString) {
    const movesContainer = document.getElementById('movesResult');
    movesContainer.innerHTML = ''; 

    const movesArray = movesString.trim().split(/\s+/);

    const spans = movesArray.map((move, index) => {
        const span = document.createElement('span');
        span.innerText = move.trim();
        span.id = `move-${index}`;
        span.style.padding = '0 4px';
        movesContainer.appendChild(span);
        return span;
    });

    return spans; 
}

function highlightMove(current_move) {
    if (current_move == 0) {
        var second_letter = document.getElementById("move-" + 1);
        second_letter.classList.remove('highlight');
        var first_letter = document.getElementById("move-" + 0);
        first_letter.classList.add('highlight');
    }
    else if (current_move == all_moves.length - 1) {
        var last_letter = document.getElementById("move-" + current_move);
        last_letter.classList.add('highlight');
        var previous_letter = document.getElementById(`move-${current_move - 1}`);
        previous_letter.classList.remove('highlight');
    }
    else {
        var next_move_index = `move-${current_move + 1}`;
        var move_index = "move-" + current_move;
        var previous_move_index = `move-${current_move - 1}`;
        var next_move_span = document.getElementById(next_move_index);
        var current_move_span = document.getElementById(move_index);
        var previous_move_span = document.getElementById(previous_move_index);
        next_move_span.classList.remove('highlight');
        current_move_span.classList.add('highlight');
        previous_move_span.classList.remove('highlight');
    }
}

let current_move;
document.addEventListener('keydown', (event) => {
    switch (event.key) {
        case 'ArrowRight':
            handleMove(all_moves[current_move])
            current_move = Math.min(all_moves.length, current_move + 1)
            break
        case 'ArrowLeft':  
            let c = current_move
            current_move = Math.max(0, current_move - 1)
            if (c > 0) {
                handleMove(getInverseMove(all_moves[current_move]))
            }
            break
    }
    highlightMove(current_move);
})


// Function to set up the form listener
function setupFormListener() {
    document.getElementById('pieces').addEventListener('keydown',  function(event) {
        if (event.keyCode === 13) {
            document.getElementById('formButton').click();
        }
    });

    const cornerButton = document.getElementById('corners');
    cornerButton.classList.add("active");
    const edgeButton = document.getElementById('edges');

    document.getElementById('pieces').addEventListener('submit', async (event) => {
        event.preventDefault();
        const first = document.getElementById('firstPiece').value;
        const second = document.getElementById('secondPiece').value;
        document.getElementById('firstPieceName').innerHTML = first;
        document.getElementById('secondPieceName').innerHTML = second;

        let url = ''

        //if (cornerButton.classList.contains('active')) url = `http://127.0.0.1:5000/get_algorithm/corners?firstPiece=${cornersMap.get(first)}&secondPiece=${cornersMap.get(second)}`;
        //else if (edgeButton.classList.contains('active')) url = `http://127.0.0.1:5000/get_algorithm/edges?firstPiece=${edgesMap.get(first)}&secondPiece=${edgesMap.get(second)}`;

        if (cornerButton.classList.contains('active')) url = `https://3styleapi.vercel.app/get_algorithm/corners?firstPiece=${cornersMap.get(first)}&secondPiece=${cornersMap.get(second)}`;
        else if (edgeButton.classList.contains('active')) url = `https://3styleapi.vercel.app/get_algorithm/edges?firstPiece=${edgesMap.get(first)}&secondPiece=${edgesMap.get(second)}`;

        try {
            const response = await fetch(url, { method: 'GET' });

            if (!response.ok) {
                throw new Error('Failed to fetch the algorithm');
            }
            const data = await response.json();

            if (data.comm == '' && data.moves == '') {
                alert("Cannot cycle to same piece!");
                document.getElementById('commResult').innerText = `No comm exists`;
                document.getElementById('movesResult').innerText = `No moves exist`;
            } else {
                document.getElementById('commResult').innerText = `${data.comm}`;
                document.getElementById('movesResult').innerText = `${data.moves}`;
                initialize();
                rotateCube(data.moves);
                displayMoves(data.moves)
                current_move = 0; 
                highlightMove(current_move);
            }
        } catch (error) {
            console.error('Error:', error);
            document.getElementById('commResult').innerText = 'Error fetching algorithm.';
            document.getElementById('movesResult').innerText = 'Error fetching algorithm.';
        }
    });
}


